### ISSUE TITLE
JSONDecodeError at /homepage/

### ISSUE THREAD

**Issue by abhijitbonik** [arishrehmankhan/visitor_logger#1]
https://github.com/arishrehmankhan/visitor_logger/blob/ba7c07b9244bb80a000da49816d86ab0d78051c7/logger/IPAddressLocation.py#L26

Request Method: | GET
-- | --
http://localhost:8000/homepage/
3.0.3
JSONDecodeError
Expecting value: line 1 column 1 (char 0)
/usr/lib64/python3.6/json/decoder.py in raw_decode, line 357
/home/spoken/projects/visitor_logger/venv/bin/python3
3.6.8
['/home/spoken/projects/visitor_logger',  '/usr/lib64/python36.zip',  '/usr/lib64/python3.6',  '/usr/lib64/python3.6/lib-dynload',  '/home/spoken/projects/visitor_logger/venv/lib64/python3.6/site-packages',  '/home/spoken/projects/visitor_logger/venv/lib/python3.6/site-packages']
Thu, 5 Mar 2020 18:04:07 +0530

**Comment by abhijitbonik** [comment]
specify the version of python you are using

**Comment by arishrehmankhan** [comment]
I am using version 3.7.4  of python

**Comment by abhijitbonik** [comment]
We have tested your system with python 3.6.9 and found this error. Please kindly check.

**Comment by arishrehmankhan** [comment]
I have checked it on version 3.6.9, but I am not getting any error.
I think the 'http://free.ipwhois.io/json' is not returning data in your machine.
I have handled this exception but was not able to find why it is not returning data to your machine.
I have also changed http:// to https://, hope it will fix the error. 
Please visit http://free.ipwhois.io/json/8.8.8.8 from your browser and see if you are getting the location data in json format.
I problem persists please let me know I will try again to solve it.
